id: 44096456-af98-45b0-8e48-531f647f426f
version: 7
vcShouldKeepItemLegacyProdMachine: false
name: DSPM Jira Ticket Creation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bf838bc6-fd32-4cfb-8907-d8ab44600b88
    type: start
    task:
      id: bf838bc6-fd32-4cfb-8907-d8ab44600b88
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "42"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "33":
    id: "33"
    taskid: 849ba9fa-f6b4-4ea8-80be-59ab250c97c8
    type: regular
    task:
      id: 849ba9fa-f6b4-4ea8-80be-59ab250c97c8
      version: -1
      name: OverwriteListAndNotify
      description: This automation script overwrites the value of a specified list
        and sends a Slack notification to inform the user that they failed to respond
        to an incident notification in a timely manner. The notification includes
        a message indicating the end of the incident playbook and an invitation to
        reopen the incident if necessary.
      scriptName: DSPMOverwriteListAndNotify
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      list_name:
        simple: ${block_list_name}
      message:
        simple: 'JIRA Ticket created successfully with ID: ${Ticket.Id} on Project
          Key: ${Ticket.Key}. Associated XSOAR incident ID: ${incident.id}.'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -360,
          "y": 2335
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "42":
    id: "42"
    taskid: 6aa28619-4d8a-47fb-827a-bb26317e726c
    type: regular
    task:
      id: 6aa28619-4d8a-47fb-827a-bb26317e726c
      version: -1
      name: Create Jira Issue without Assignee ID
      description: Creates a new issue in Jira.
      script: '|||jira-create-issue'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "54"
    scriptarguments:
      description:
        simple: |-
          Risk Details :
          XSOAR Incident ID: ${incident.get('id')}
          DSPM Risk ID: ${incident.get('riskfindingid')}
          Rule Name: ${incident.get('riskname')}
          Risk Severity: ${incident.get('severity')}
          Asset Name: ${incident.get('assetname')}
          Asset ID: ${incident.get('assetid')}
          Risk Status : ${incident.get('status)}
          Project ID: ${incident.get('projectid')}
          Cloud Provider: ${incident.get('cloud')}
          serviceType: ${incident.get('serviceType')}
          First Detected On: ${incident.get('firstdetectedon')}
          Remediate Instruction: ${incident.get('remediateinstruction')}
      issue_type_name:
        simple: ${User.JiraTicketType}
      project_name:
        simple: ${User.JiraProjectName}
      summary:
        simple: 'The issue created from XSOAR incident Id: ${incident.id} of DSPM
          risk : ${incident.riskfindingid}. Rule Name: ${incident.riskname}'
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 1630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "43":
    id: "43"
    taskid: 78a8f56b-7686-4466-826f-dcefcbb782d5
    type: regular
    task:
      id: 78a8f56b-7686-4466-826f-dcefcbb782d5
      version: -1
      name: Update Slack Incident with JIRA details
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "33"
    scriptarguments:
      details:
        simple: 'JIRA Ticket created successfully with ID: ${Ticket.Id} and Key: ${Ticket.Key}.
          Associated Remediation ID: ${riskFindingId}. The ticket is not assigned
          to anybody because an error occurred when retrieving the assignee ID for
          ${User.Email} from Jira.'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -360,
          "y": 2080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "54":
    id: "54"
    taskid: 6f0b05ed-e4e7-4f09-8201-263531e8ea3c
    type: condition
    task:
      id: 6f0b05ed-e4e7-4f09-8201-263531e8ea3c
      version: -1
      name: Is there an error when creating a Jira ticket?
      description: This script checks for error entries based on provided entry IDs
        and returns "yes" if any errors are found or "no" if no errors are present.
        If errors are detected, it sets the error messages in the XSOAR context.
      scriptName: DSPMCheckAndSetErrorEntries
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "43"
      "yes":
      - "55"
    scriptarguments:
      entry_id:
        simple: ${lastCompletedTaskEntries}
    results:
    - ErrorEntries
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 1840
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "55":
    id: "55"
    taskid: 1c8449db-8ab5-47c1-8790-fefc9afc58d2
    type: playbook
    task:
      id: 1c8449db-8ab5-47c1-8790-fefc9afc58d2
      version: -1
      name: DSPM notify user in case of error
      playbookName: DSPM notify user in case of error
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 380,
          "y": 2080
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1000,
        "width": 1120,
        "x": -360,
        "y": 1430
      }
    }
  }
inputs: []
inputSections:
- inputs: []
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
sourceplaybookid: da7fa1c4-11b7-4c6c-8afa-15d0e3e5f417
dirtyInputs: true
